### PR TITLE
Bit of data reformatting

### PR DESCRIPTION
**Pull request by marksteward**
This makes it nicer to work with in JS.

### CODE REVIEW

**Comment by marksteward** [comment]
Looks like GitHub's added my viewer commit to this PR as well 🤷

**Comment by Jonty** [comment]
Can you PR this without the geojson/kml changes, that way the GHA will just regenerate them and avoid conflicts

**Comment by marksteward** [comment]
I'd included the changes so the preview would look right, but I've removed them now.

**Comment by Jonty** [comment]
Merrrrrged 🎉

**Pull request merged**
